In [2]:
import numpy as np

In [3]:
#Criando uma matriz Python

def geramatriz(l=2, c=2,rand=False,r1=0,r2=50):
    '''
    :param l: Linhas
    :param c: Colunas
    :return: A matriz gerada com o valor escolhido
    '''
    mat = [[0] * c for z in range(l)]
    if rand:
        return preenchematriz(mat, r1, r2)
    return mat

#preenchendo a matriz 

def preenchematriz(mat, r1=0, r2=50):
    from random import randint
    '''
    :param mat: Qual matriz
    :param r1: valor minimo
    :param r2: valor máximo
    :return: a matriz preenchida
    '''
    for j in range(len(mat[0])):
        for k in range(len(mat)):
            mat[k][j] = randint(r1, r2)
    return mat

In [4]:
#A soma de matrizes ocorre apenas entre matrizes de mesmo tamanho e 
# é a soma de cada espaço individualmente
def soma_matrizes(A:list[list[int]], B:list[list[int]]) -> list[list[int]]:
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        return None
    C= [[0] * len(A[0]) for z in range(len(A))]
    for i in range(len(A)):
        for j in range(len(A[0])):
            C[i][j]=A[i][j] + B[i][j]
    return C
#A subtração de matrizes pode ser entendida como a soma de A pelo inverso de B, 
# ou seja A + (-B)
def sub_matrizes(A:list[list[int]], B:list[list[int]]) -> list[list[int]]:
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        return None
    C= [[0] * len(A[0]) for z in range(len(A))]
    for i in range(len(A)):
        for j in range(len(A[0])):
            C[i][j]=A[i][j] - B[i][j]
    return C

In [5]:
#Exemplo de soma de matrizes
mat1=geramatriz(4,5,True)
mat2=geramatriz(4,5,True)
soma_matrizes(mat1,mat2)

[[55, 59, 55, 84, 39],
 [14, 63, 77, 56, 50],
 [32, 41, 80, 35, 50],
 [43, 62, 54, 34, 58]]

In [7]:
#A multiplicação da matriz por um número é a multiplicação de cada termo pelo valor
mat=np.random.randint(0,50,20).reshape(2,10)
print(mat,'\n')
print(mat*2,'\n')

print(mat/2,'\n')

[[28 49  3 13 39  5 11  3 43  5]
 [32 36  1  5 20 49 19 24 37 45]] 

[[56 98  6 26 78 10 22  6 86 10]
 [64 72  2 10 40 98 38 48 74 90]] 

[[14.  24.5  1.5  6.5 19.5  2.5  5.5  1.5 21.5  2.5]
 [16.  18.   0.5  2.5 10.  24.5  9.5 12.  18.5 22.5]] 



In [ ]:
#Produto de duas matrizes
