In [20]:
import numpy as np

In [13]:
#Criando uma matriz Python

def geramatriz(l=2, c=2,rand=False,r1=0,r2=50):
    '''
    :param l: Linhas
    :param c: Colunas
    :return: A matriz gerada com o valor escolhido
    '''
    mat = [[0] * c for z in range(l)]
    if rand:
        return preenchematriz(mat, r1, r2)
    return mat

#preenchendo a matriz 

def preenchematriz(mat, r1=0, r2=50):
    from random import randint
    '''
    :param mat: Qual matriz
    :param r1: valor minimo
    :param r2: valor máximo
    :return: a matriz preenchida
    '''
    for j in range(len(mat[0])):
        for k in range(len(mat)):
            mat[k][j] = randint(r1, r2)
    return mat

In [21]:
#A soma de matrizes ocorre apenas entre matrizes de mesmo tamanho e 
# é a soma de cada espaço individualmente
def soma_matrizes(A:list[list[int]], B:list[list[int]]) -> list[list[int]]:
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        return None
    C= [[0] * len(A[0]) for z in range(len(A))]
    for i in range(len(A)):
        for j in range(len(A[0])):
            C[i][j]=A[i][j] + B[i][j]
    return C
#A subtração de matrizes pode ser entendida como a soma de A pelo inverso de B, 
# ou seja A + (-B)
def sub_matrizes(A:list[list[int]], B:list[list[int]]) -> list[list[int]]:
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        return None
    C= [[0] * len(A[0]) for z in range(len(A))]
    for i in range(len(A)):
        for j in range(len(A[0])):
            C[i][j]=A[i][j] - B[i][j]
    return C

In [19]:
#Exemplo de soma de matrizes
mat1=geramatriz(4,5,True)
mat2=geramatriz(4,5,True)
soma_matrizes(mat1,mat2)

[[29, 75, 62, 35, 34],
 [34, 69, 38, 52, 84],
 [41, 67, 4, 45, 72],
 [8, 33, 68, 55, 60]]

In [26]:
#A multiplicação da matriz por um número é a multiplicação de cada termo pelo valor
mat=np.random.randint(0,50,20).reshape(2,10)
print(mat)
mat*2

[[43 10  5 14 28  5 37 37 19 37]
 [30 20  1 37  5 42 38 41 29 27]]


array([[86, 20, 10, 28, 56, 10, 74, 74, 38, 74],
       [60, 40,  2, 74, 10, 84, 76, 82, 58, 54]])